FLOW_NAME = 500-SIGNOFF/520-sta
FLOW_PATH = .flow/$(FLOW_NAME)

include $(FLOW_PATH)/flow.options
include $(FLOW_PATH)/flow.files
#include $(FLOW_PATH)/flow.steps
include flow.steps
include $(FLOW_PATH)/flow.targets

include makefile.flow

